#!/bin/bash

PVC="$1"

cat <<EOF > exporter_file.yaml
apiVersion: v1
kind: Pod
metadata:
  name: exporter
spec:
  containers:
  - name: exporter
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /data
      name: export-pvc
  volumes:
  - name: export-pvc
    persistentVolumeClaim:
      claimName: ${PVC}
EOF


upload_yaml master1  exporter_file.yaml

while [[ ` ssh-vm -r master1 -c "kubectl get pod/exporter" \
	 | awk '/exporter/ {print $3}' ` != "Running" ]]
do
	sleep 1;
done

DATE=$( date +%Y-%m-%d-%H-%M-%S-%s )

ssh-vm -r master1 -c "kubectl cp exporter:/data ./backup-${DATE}"
ssh-vm -r master1 -c "kubectl delete pod/exporter"
ssh-vm -r master1 -c "tar -cvf backup-${DATE}.tar ./backup-${DATE}"

exec 2>/dev/null
scp -i ~/.ssh/id_internal_vm root@$( get-ip master1 ):./backup-${DATE}.tar ./

rm exporter_file.yaml
