.\" Manpage for boot-servers
.TH BOOT-SERVERS 1 "Octubre 2025" "1.0" "Comandos de usuario"
.SH NOMBRE
boot-servers \- utilidad de apoyo para iniciar los servidores NAT
.SH SINOPSIS
.B boot-servers \(->\~ inicia solo el NAT-master por defecto
.br
.B boot-servers [\fB -b iniciar Backup?\fR]

.SH DESCRIPCION
\fBboot-servers\fR utilidad para iniciar los servidores, se puede decidir si solo se inicia el master o también se inicia el NAT-Backup
.SH OPCIONES
.TP
\fB-b\fR 
.TP
	iniciar el NAT-Backup como respaldo del NAT-Master
.SH AUTORES
.TP
Anubis Correa
.TP
José Alejandro Arias
