.\" Manpage for backup
.TH CLEAN-CLUSTER 1 "Octubre 2025" "1.0" "Comandos de usuario"
.SH NOMBRE
clean-cluster \- utilidad para eliminar todo el cluster
.SH SINOPSIS
.B clean-cluster
.br
.B clean-cluster
[\fB-y\fR]

.SH DESCRIPCION
\fBclean-cluster\fR utilidad para limpiar el cluster, pausa y borra todos los nodos dentro del hipervisor
.SH OPCIONES
.TP
\fB-y\fR
omite la confirmación antes de eliminar el cluster
.SH AUTORES
.TP
Anubis Correa
.TP
José Alejandro Arias
