.\" Manpage for get-ip
.TH GET-IP 1 "Octubre 2025" "1.0" "Comandos de usuario"
.SH NOMBRE
get-ip \- utilidad para obtener la ip de una vm dentro del cluster
.SH SINOPSIS
.B get-ip <vm-name>
.br
.SH DESCRIPCION
\fBget-ip\fR utilidad para obtener la ip de una vm dentro del cluster
.SH EJEMPLOS
.TP
obtiene la ip de la vm master1
.br
.TP
	$ get-ip master1
.SH AUTORES
.TP
Anubis Correa
.TP
José Alejandro Arias
