#!/bin/bash

# ensures file cleanup after cancellation

trap "rm -f exporter_file.yaml" SIGINT

MODE="pvc"
TARGET=""
POD=""
FOLDER=""
while getopts "p:f:" opt; do
  case "$opt" in
    p) MODE="pod"; POD="$OPTARG" ;;     # backup from pod:path
    f) MODE="folder"; FOLDER="$OPTARG" ;; # backup from host path
  esac
done
shift $((OPTIND-1))

NODE="$( get-vm -a -n 1 master )"

PVC="$1"
DATE=$( date +%Y-%m-%d-%H-%M-%S-%s )

if [[ "$MODE" == "pvc" ]]; then
  # --- current PVC backup flow ---
  cat <<EOF > exporter_file.yaml
apiVersion: v1
kind: Pod
metadata:
  name: exporter
spec:
  containers:
  - name: exporter
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /data
      name: export-pvc
  volumes:
  - name: export-pvc
    persistentVolumeClaim:
      claimName: ${PVC}
EOF

  upload_yaml ${NODE} exporter_file.yaml

  while [[ $(ssh-vm -r ${NODE} -c "kubectl get pod/exporter -o jsonpath='{.status.phase}'") != "Running" ]]; do
    sleep 1
  done
  FILENAME="/tmp/backup-${DATE}-pvc.tar"
  ssh-vm -r ${NODE} -c "kubectl cp exporter:/data ./backup-${DATE}"
  ssh-vm -r ${NODE} -c "kubectl delete pod/exporter"
  ssh-vm -r ${NODE} -c "tar -cvf ${FILENAME} ./backup-${DATE}"

elif [[ "$MODE" == "pod" ]]; then
  FILENAME="/tmp/backup-${DATE}-pod.tar"
  # --- backup arbitrary path from pod ---
  ssh-vm -r ${NODE} -c "kubectl cp ${POD} ./backup-${DATE}"
  ssh-vm -r ${NODE} -c "tar -cvf ${FILENAME} ./backup-${DATE}"

elif [[ "$MODE" == "folder" ]]; then
  FILENAME="/tmp/backup-${DATE}-node.tar"
  # --- backup arbitrary folder from node ---
  NODE=$( echo $FOLDER | cut -d":" -f1 )
  FOLDER=$( echo $FOLDER | cut -d":" -f2 ) 
  echo "++++++ $NODE ++++ $FOLDER +++"
  ssh-vm -r ${NODE} -c "tar -cvf ${FILENAME} ${FOLDER}"
fi

exec 2>/dev/null
scp -i ~/.ssh/id_internal_vm root@$(get-ip ${NODE}):"${FILENAME}" ./

rm -f exporter_file.yaml
