#!/bin/bash

BANNER="┌───────────────────────────────────────────────────────┐
│  _____ _____  _____ _____      __      ______   _____ │
│ / ____|  __ \|_   _|  __ \     \ \    / /  _ \ / ____|│
│| |  __| |__) | | | | |  | |_____\ \  / /| |_) | |     │
│| | |_ |  _  /  | | | |  | |______\ \/ / |  _ <| |     │
│| |__| | | \ \ _| |_| |__| |       \  /  | |_) | |____ │
│ \_____|_|  \_\_____|_____/         \/   |____/ \_____|│
│                                                       │
│                                                       │
└───────────────────────────────────────────────────────┘
"

export NEWT_COLORS='
root=white,blue'

while true; do
    # Main menu with whiptail
    choice=$(whiptail --title "Menú Principal" \
        --menu "$BANNER\nSeleccione una opción:" 30 62 10 \
        "1" "Subir archivo" \
        "2" "Limpiar cluster" \
        "3" "Backup" \
        "4" "Agregar VM al cluster" \
        "5" "SSH" \
        "6" "Inicializar cluster" \
        "7" "Salir" \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus -ne 0 ] || [ "$choice" == "7" ]; then
        echo "Saliendo..."
        break
    fi

    case $choice in
        "1")
            node=$(whiptail --inputbox "Ingrese el nodo:" 10 60 3>&1 1>&2 2>&3)

	    [ $? -ne 0 ] && continue

            file=$(whiptail --inputbox "Ingrese el archivo:" 10 60 3>&1 1>&2 2>&3)

	    [ $? -ne 0 ] && continue

            echo "Ejecutando: upload_yaml $node $file"
            upload_yaml "$node" "$file"
            ;;
        "2")
            echo "Ejecutando: clean-cluster"
            clean-cluster
            ;;
        "3")
            backup_choice=$(whiptail --title "Opciones de Backup" \
                --menu "Seleccione el tipo de backup:" 20 60 10 \
                "1" "Backup para PVC" \
                "2" "Backup para Pod" \
                "3" "Backup para Nodo" \
                3>&1 1>&2 2>&3)

	    [ $? -ne 0 ] && continue

            case $backup_choice in
                "1")
                    pvc=$(whiptail --inputbox "Ingrese el PVC:" 10 60 3>&1 1>&2 2>&3)
		    [ $? -ne 0 ] && continue
                    echo "Ejecutando: backup-pvc $pvc"
                    backup "$pvc"
                    ;;
                "2")
                    pod_route=$(whiptail --inputbox "Ingrese el pod-route:" 10 60 3>&1 1>&2 2>&3)
		    [ $? -ne 0 ] && continue
                    echo "Ejecutando: backup-pod $pod_route"
                    backup -p "$pod_route"
                    ;;
                "3")
                    carpeta=$(whiptail --inputbox "Ingrese la carpeta:" 10 60 3>&1 1>&2 2>&3)
		    [ $? -ne 0 ] && continue
                    echo "Ejecutando: backup-nodo $carpeta"
                    backup -f "$carpeta"
                    ;;
            esac
            ;;
        "4")
            vm_name=$(whiptail --inputbox "Ingrese el nombre de la VM:" 10 60 3>&1 1>&2 2>&3)
	    [ $? -ne 0 ] && continue
            echo "Ejecutando: bootvm -j $vm_name"
            bootvm -j "$vm_name"
            ;;
        "5")
            vm_name=$(whiptail --inputbox "Ingrese el nombre de la VM:" 10 60 3>&1 1>&2 2>&3)
	    [ $? -ne 0 ] && continue
            echo "Ejecutando: ssh-vm $vm_name"
            ssh-vm "$vm_name"
            ;;
        "6")
            masters=$(whiptail --inputbox "Ingrese la cantidad de masters:" 10 60 3>&1 1>&2 2>&3)
	    [ $? -ne 0 ] && continue
            workers=$(whiptail --inputbox "Ingrese la cantidad de workers:" 10 60 3>&1 1>&2 2>&3)
	    [ $? -ne 0 ] && continue
	    nat_backup=$(whiptail --title "Opciones adicionales" \
	       --checklist "Seleccione si desea agregar NAT-Backup:" 15 60 5 \
	       "1" "Agregar NAT-Backup" OFF \
	       3>&1 1>&2 2>&3 )

	    [ $? -ne 0 ] && continue

            [ $nat_backup -eq 1 ] && nat_backup="-b"

            echo "Ejecutando: cluster-bootup -m $masters -w $workers $nat_backup"
            cluster-bootup -m "$masters" -w "$workers" $nat_backup
            ;;
    esac
done
