#!/bin/bash

# Sube un archivo .yaml al cluster y lo
# ejecuta como recurso de kubernetes
exec 2> /dev/null

NODE="$1"
shift   

IP=$( get-ip "$NODE" )

for FILE in "$@"; do
    FILENAME=$( basename "$FILE" )
    scp -i ~/.ssh/id_internal_vm "$FILE" root@$IP:./
    ssh -i ~/.ssh/id_internal_vm root@$IP "kubectl apply -f $FILENAME && rm $FILENAME"
done
